# This specification is in transition to `gitlab-templates`. Some required
# features are not implemented yet, so relevant jobs are commented-out. In
# particular:
#  - Windows CI
#  - separate `build` of LangKit/LAL/ALS/GS
#  - testing of GNATdoc/LSIF-Ada/GNATformat/etc

stages:
  - build
  - test
  - check
  - downstream:build
  - downstream:test

include:
# Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

# Build (stable & edge)
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build:stable:linux
      anod-args: run build_stable --latest
      save-component: true

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      job-name: build:edge:linux
      anod-args: run build_edge --latest
      save-component: true

#  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
#    inputs:
#      job-name: build:edge:windows
#      anod-args: run build_edge --latest
#      cpu:8
#      image: e3-windows-core-2022
#      save-component: true
#        #    variables:
#        #      ACI_TRACK: edge
#    services:
#      - platform:x86_64-windows-2022
#      - image:e3-windows-core-2022

# Testing (stable & edge)
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: test:stable:linux
      needs: ["build:stable:linux"]
      cpus: 2
      # --latest should not be used here because it causes Anod to re-download
      # components from Cathod instead of using the ones built in this pipeline
      # by the build job.
      anod-args: run test_stable

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: test:edge:linux
      needs: ["build:edge:linux"]
      cpus: 2
      # --latest should not be used here because it causes Anod to re-download
      # components from Cathod instead of using the ones built in this pipeline
      # by the build job.
      anod-args: run test_edge

# Downstream build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: downstream:build
      needs: ["build:edge:linux"]
      job-name: build:edge:linux:prettier-ada
      anod-args: run build_edge_prettier_ada
      cpus: 16
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
      save-component: true

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: downstream:build
      needs: ["build:edge:linux:prettier-ada"]
      job-name: build:edge:linux:gnatdoc
      anod-args: run build_edge_gnatdoc
      cpus: 16
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
      save-component: true

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: downstream:build
      needs: ["build:edge:linux:gnatdoc"]
      job-name: build:edge:linux:als
      anod-args: run build_edge_als
      cpus: 16
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
      save-component: true

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      stage: downstream:build
      needs: ["build:edge:linux:als"]
      job-name: build:edge:linux:gs
      anod-args: run build_edge_gs
      image: systemgtk
      cpus: 16
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
      save-component: true

# Downstream testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      stage: downstream:test
      needs: ["build:edge:linux:prettier-ada"]
      job-name: test:edge:linux:prettier-ada
      anod-args: run test_edge_prettier_ada
      cpus: 16

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      stage: downstream:test
      needs: ["build:edge:linux:gnatdoc"]
      job-name: test:edge:linux:gnatdoc
      anod-args: run test_edge_gnatdoc
      cpus: 16

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      stage: downstream:test
      needs: ["build:edge:linux:als"]
      job-name: test:edge:linux:als
      anod-args: run test_edge_als
      cpus: 16

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      stage: downstream:test
      needs: ["build:edge:linux:gs"]
      job-name: test:edge:linux:gs
      anod-args: run test_edge_gs
      image: systemgtk
      cpus: 16

###########################
# LEGACY BUILD ON WINDOWS #
###########################

.build_and_test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - generic_anod_ci
    - . /tmp/ci_env.sh
    # Build & test using anod
    - anod build vss $ACI_TRACK_QUALIFIER --latest
    - anod test vss $ACI_TRACK_QUALIFIER --latest
    - testsuite_reports

build_and_test:windows:
  extends: .build_and_test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  services:
     - image:e3-windows-core-2022
     - cpu:8
     - platform:x86_64-windows-2022
