.basic-setup:
  - |
    set -x
    export PATH=/it/e3/bin:$PATH
  - . ~/.aws_container_credentials

stages:
  - build_and_test
  - build_dependent

#########
# BUILD #
#########

build_and_test:
  services:
     - image:sandbox
     - cpu:8
     - mem:16
  stage: build_and_test
  script:
    - !reference [.basic-setup]

    - |
      # Install GNAT (with gcov) and gcovr
      anod install --sandbox-dir /it/wave gnatall
      python3 -m pip install gcovr

      # Fetch tests' data into `./data/`
      PACKAGE=vss-tests-data.tar.bz2
      VSS_URL=https://gitlab.adacore-it.com/api/v4/projects/129
      curl -L --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        $VSS_URL/packages/generic/$PACKAGE/0.0.0/$PACKAGE |\
        tar xjf - -C ./data

      # Build VSS and run tests
      ( eval $(anod printenv --sandbox-dir /it/wave gnatall) ;\
        make COVERAGE_MODE=gcov build-libs-static check ;\
        ENABLE_GCOV=y gcovr --print-summary --cobertura gcov.xml )
      make clean

  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: gcov.xml

build_als:
  services:
     - image:sandbox
     - cpu:8
     - mem:16
  stage: build_dependent
  script:
    - !reference [.basic-setup]

    - |
      cd /it/wave

      # Tell the anod sandbox to use our repository
      anod vcs --add-repo vss $CI_PROJECT_DIR

      # Build the ALS as a test
      anod build als

build_gs:
  services:
     - image:gtk-deps
     - cpu:8
     - mem:16
  stage: build_dependent
  when: manual
  script:
    - !reference [.basic-setup]

    - |
      cd /it/wave

      # Tell the anod sandbox to use our repository
      anod vcs --add-repo vss $CI_PROJECT_DIR

      # Build the ALS as a test
      anod build gps
