stages:
  - build_and_test

#########
# BUILD #
#########

build_and_test:
  services:
     - image:sandbox
     - cpu:8
     - mem:16
  stage: build_and_test
  script: |
    set -x
    . ~/.aws_container_credentials
    export PATH=/it/e3/bin:$PATH

    # Install GNAT (with gcov) and gcovr
    anod install --sandbox-dir /it/wave gnatall
    python3 -m pip install gcovr

    # Fetch tests' data into `./data/`
    PACKAGE=vss-tests-data.tar.bz2
    VSS_URL=https://gitlab.adacore-it.com/api/v4/projects/129
    curl -L --header "JOB-TOKEN: $CI_JOB_TOKEN" \
     $VSS_URL/packages/generic/$PACKAGE/0.0.0/$PACKAGE |\
     tar xjf - -C ./data

    # Build VSS and run tests
    ( eval $(anod printenv --sandbox-dir /it/wave gnatall) ;\
      make COVERAGE_MODE=gcov build-libs-static check ;\
      ENABLE_GCOV=y gcovr --print-summary --cobertura gcov.xml )
    make clean

    # Tell the anod sandbox to use our repository
    cd /it/wave
    anod vcs --add-repo vss $CI_PROJECT_DIR

    # Build the ALS as a test
    anod build als

  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: gcov.xml
