os: linux

language: generic

services:
 - docker

install:
 - docker pull ubuntu:18.04

script:
 - docker build --build-arg=CODECOV_TOKEN=$CODECOV_TOKEN .

env:
  global:
    secure: A3wTiWJRY331+YhvZdiQsLGG4RVlvX9x7nsmuYVAfsKovsLFnTzVWqXv7HnZwnzJMTPHnApqTpUZrkgE7IjZU2qlY7OvPL9DQyRsnusowP1wXPgLu8/KgMU0WIa3naYn4J+EQdZXoAkj7nwK3EsGpC4LwcD6wdxDDMXmMS9ttK0hqPbivpJo0IW1QHCLLnMeHaj52snlOFKzUJZhkuuCWMb4HpTT6JXY2hEPZgkwGLamDA8JB+LsfRgEwciizPzEHbRUgjkLie6VAcFX92jlP/hmUMUA/97PJm7/BAd8zd7k456xVr7YG0N+BoI2Hz4pAaYMpUCPAhav1FKGq4S+nBP+TGAVXUNLv4jqmaTUC+Ln6bneCcfbVMtLi8UPAlYQ7864w6SyJww/iKpINuU/FD8+S6DNIxnJp8D75yG0WEmHiM0x7vnqQEk4H5oyNQ2TEcCa/MY/txs4wYZAFX/JYoR4eKC1WI3QajNhWHnEdtFJZ7Q+pIFuEO0gWjDDrJUs/VQaYEw2JQ1VHJWCFUxtzgEuhd6TGhrI51xOH88H9kh6BBL9U2x1T+o/aiA1iG/aKdVgLSTSAEh5/HTO+KJ3J0Wv4cxVMfjH7y7vI8/Sd0hk2uaneIKBFRqI3iqWcM44xi0F38heYtqq8JqjRiISwWnPHxWagq0oYF1dXIqjqNg=

