name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "22.0.0-20210830"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr"]

[configuration]
generate_ada = false
generate_c = false
