name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "25.0.0-dev"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr"]

[configuration]
generate_ada = false
generate_c = false

[configuration.variables]
Max_Supported_Integer_Size = {type = "Enum", values = ["128", "64"], default = "128"}

[build-switches]
"*".ada_version = "Ada2022"
