name = "vss"
description = "Virtual String System - a high level string and text processing library"

long-description = """
## Deprecation

This crate is deprecated. VSS has been split into smaller more focused
projects:

* [`vss_text`](https://alire.ada.dev/crates/vss_text): a library for Unicode text
  processing.
* [`vss_extra`](https://alire.ada.dev/crates/vss_extra): libraries for handling
  JSON, Regexp, XML and other features based on `vss_text`. This will be
  further split into smaller projects.

This crate is kept as a read-only historic snapshot that will no longer
evolve. Please refer to the above crates to continue using their
corresponding features, and to be informed of upcoming changes.
"""

version = "25.0.0-dev"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr"]

[configuration]
generate_ada = false
generate_c = false

[configuration.variables]
Max_Supported_Integer_Size = {type = "Enum", values = ["128", "64"], default = "128"}

[build-switches]
"*".ada_version = "Ada2022"
