on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [dev, prod, coverage]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - name: Get VSS
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./cached_gnat
          key: ${{ runner.os }}-gnat-ce-2021
          restore-keys: ${{ runner.os }}-gnat-ce-2021
      - name: Get GNAT Community 2021 toolchain
        if: ${{ runner.os != 'macOS' }}
        uses: ada-actions/toolchain@ce2021
        with:
          distrib: community
          install_dir: ./cached_gnat
      - name: Get GNAT Community 2020 toolchain
        if: ${{ runner.os == 'macOS' }}
        uses: ada-actions/toolchain@ce2020
        with:
          distrib: community
          install_dir: ./cached_gnat
      - name: Get UCD.zip
        run: |
          curl -C - -o ./cached_gnat/UCD-13.0.0.zip https://www.unicode.org/Public/13.0.0/ucd/UCD.zip
          mkdir data
          mkdir data/ucd
          unzip cached_gnat/UCD-13.0.0.zip -d ./data/ucd
      - name: Build and test
        run: |
          make all check coverage BUILD_MODE=${{ matrix.build_mode }}
          make install check_install PREFIX=/tmp BUILD_MODE=${{ matrix.build_mode }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.build_mode == 'coverage' }}
