on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [dev, prod, coverage]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - name: Get VSS
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./cached_gnat
          key: ${{ runner.os }}-gnat-2020.1
          restore-keys: ${{ runner.os }}-gnat-2020.1
      - name: Get GNAT Community 2020 toolchain
        uses: ada-actions/toolchain@ce2020
        with:
          distrib: community
          install_dir: ./cached_gnat
      - name: Build and test
        run: make all check coverage BUILD_MODE=${{ matrix.build_mode }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.build_mode == 'coverage' }}
