on: [push, pull_request]
name: Spell checks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get VSS
        uses: actions/checkout@v2
        with:
          path: ./vss
      - name: Install aspell
        run: sudo apt-get install -y aspell aspell-en
      - name: Run aspell
        run: make -C vss spellcheck
